---

- hosts: all
  become: true
  tasks:

  - name: dnf update repositories
    dnf:
      update_cache: true
    when: ansible_distribution == "RedHat"

  - name: dnf install docker packages
    dnf:
      name:
        - docker.io
        - docker-compose
    when: ansible_distribution == "RedHat"

  - name: apt update repositories
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: apt install docker packages
    apt:
      name:
        - docker.io
        - docker-compose
    when: ansible_distribution == "Ubuntu"
