---

- hosts: docker_hosts
  become: true
  pre_tasks:

  - name: dnf update repositories and install docker packages
    tags: docker, dnf, podman, RedHat
    dnf:
      name:
        - podman-docker
      update_cache: true 
    when: ansible_distribution == "RedHat"

  - name: apt update repositories and install docker packages
    tags: docker, apt, containerd, ubuntu
    apt:
      name:
        - docker.io
        - docker-compose
      update_cache: true
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
  
  - name: create compose folder structure
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    loop:
      - /home/janik/docker-compose/
      - /home/janik/docker-compose/authentik/
      - /home/janik/docker-compose/bookstack/
      - /home/janik/docker-compose/kitchenowl/
      - /home/janik/docker-compose/nginx-pm/
      - /home/janik/docker-compose/paperless-ngx/
      - /home/janik/docker-compose/uptime-kuma/
      - /home/janik/docker-compose/vaultwarden/

  tasks:
  
  - name: copy docker-compose files from storagebox
    tags: docker-compose, yaml, storagebox
    copy:
      remote_src: true
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - src: /mnt/storage-box/docker-compose/nginx-pm/docker-compose.yml
        dest: /home/janik/docker-compose/nginx-pm/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/authentik/docker-compose.yml
        dest: /home/janik/docker-compose/authentik/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/bookstack/docker-compose.yml
        dest: /home/janik/docker-compose/bookstack/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/kitchenowl/docker-compose.yml
        dest: /home/janik/docker-compose/kitchenowl/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/paperless-ngx/docker-compose.yml
        dest: /home/janik/docker-compose/paperless-ngx/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/uptime-kuma/compose.yaml
        dest: /home/janik/docker-compose/uptime-kuma/docker-compose.yml
      - src: /mnt/storage-box/docker-compose/vaultwarden/docker-compose.yml
        dest: /home/janik/docker-compose/vaultwarden/docker-compose.yml

  - name: run docker-compose on nginx-pm
    docker_compose:
      project_src: "{{ item.dest }}"
