---

- hosts: all
  become: true
  tasks:

  - name: dnf update repositories
    dnf:
      update_cache: true
    when: ansible_distribution == "RedHat"

  - name: dnf install docker packages
    dnf:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    when: ansible_distribution == "RedHat"

  - name: apt update repositories
    apt:
      update_cache: true
    when: ansible_distribution == "Ubuntu"

  - name: apt install docker packages
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
    when: ansible_distribution == "Ubuntu"
