---

- hosts: all
  become: true
  tasks:

  - name: dnf update repositories and install docker packages
    dnf:
      name:
        - podman-docker
      update_cache: true
    when: ansible_distribution == "RedHat"

  - name: apt install docker packages
    apt:
      name:
        - docker.io
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      update_cache: true
    when: ansible_distribution in ["Ubuntu", "Debian"]
