---

- hosts: all
  become: true
  tasks:

  - name: update apt repositories
    dnf:
      update_cache: true

  - name: install docker packages
    dnf:
      name:
        - docker.io
        - docker-compose

