---

- hosts: Docker hosts
  become: true
  tasks:

  - name: dnf update repositories and install docker packages
    tags: docker, dnf, podman, RedHat
    dnf:
      name:
        - podman-docker
      update_cache: true 
    when: ansible_distribution == "RedHat"

  - name: apt update repositories and install docker packages
    tags: docker, apt, containerd, ubuntu
    apt:
      name:
        - docker.io
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      update_cache: true
      state: latest
    when: ansible_distribution in ["Ubuntu", "Debian"]
